// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABoBiZAIq0DKrTNWDVEzyFYpD9zhO7lns',
    appId: '1:733790918622:web:d8c3b46dc43d61489bef4f',
    messagingSenderId: '733790918622',
    projectId: 'mynotes-dm-flutter',
    authDomain: 'mynotes-dm-flutter.firebaseapp.com',
    storageBucket: 'mynotes-dm-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYiq07VZxir4JKx2DzHIFnn14o3PfA0yk',
    appId: '1:733790918622:android:5262fa5b9f52a91d9bef4f',
    messagingSenderId: '733790918622',
    projectId: 'mynotes-dm-flutter',
    storageBucket: 'mynotes-dm-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0cT63BSxx0BnjwgjsyFL6MIuA5jm87eM',
    appId: '1:733790918622:ios:f5dc3d4c81573ade9bef4f',
    messagingSenderId: '733790918622',
    projectId: 'mynotes-dm-flutter',
    storageBucket: 'mynotes-dm-flutter.appspot.com',
    iosClientId: '733790918622-51at8hussmks9i2ttjt2fio6m3mknsog.apps.googleusercontent.com',
    iosBundleId: 'dev.dennismichol.mynotes',
  );
}
